project:
  type: website

website:
  title: "open-company-uk methodology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - methodology.qmd
      - validation.qmd
      - limitations.qmd
      - accounts.qmd

format:
  html:
    toc: true
